"""empty message

Revision ID: 08488e129c6c
Revises: ec0c6c6f1cd3
Create Date: 2023-11-09 01:05:38.498638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08488e129c6c'
down_revision = 'ec0c6c6f1cd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost', sa.Integer(), nullable=True))
        batch_op.alter_column('created_date',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('created_date',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('cost')

    # ### end Alembic commands ###
