"""Your migration message

Revision ID: 2b63726fba53
Revises: e3389373917e
Create Date: 2023-12-24 11:27:20.938286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b63726fba53'
down_revision = 'e3389373917e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_item')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_item',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('order_id', sa.INTEGER(), nullable=True),
    sa.Column('item_id', sa.INTEGER(), nullable=True),
    sa.Column('quantity', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], name='fk_order_item_item_id_item'),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], name='fk_order_item_order_id_order'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
