"""empty message

Revision ID: 384dc3a563bf
Revises: 88494205141f
Create Date: 2023-11-08 16:03:13.584017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '384dc3a563bf'
down_revision = '88494205141f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], name=op.f('fk_order_item_item_id_item')),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], name=op.f('fk_order_item_order_id_order')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('created_date',
               existing_type=sa.DATETIME(),
               type_=sa.String(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('created_date',
               existing_type=sa.String(),
               type_=sa.DATETIME(),
               nullable=False)

    op.drop_table('order_item')
    # ### end Alembic commands ###
