"""empty message

Revision ID: c0f3545695a0
Revises: 2b63726fba53
Create Date: 2023-12-24 13:36:57.593950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0f3545695a0'
down_revision = '2b63726fba53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], name=op.f('fk_order_item_item_id_item')),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], name=op.f('fk_order_item_order_id_order')),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('cart')
    op.drop_table('user_order')
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_order_user_id_user'), 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_order_user_id_user'), type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('created')

    op.create_table('user_order',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('order_id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], name='fk_user_order_order_id_order'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_user_order_user_id_user'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cart',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('item_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], name='fk_cart_item_id_item'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_cart_user_id_user'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('order_item')
    # ### end Alembic commands ###
